language: generic
matrix:
  include:
    -language: python
    virtualenv:
      system_site_packages: true
    python: 3.5.1
    before_install: 
      - cd ./backend/
    install: 
      - pip install -r requirements.txt
    script:
      - python manage.py test

    -language: node_js
    node_js: 6.9.4
    before_install: 
      - cd ./frontend/
    install:
      - npm install 
    script: 
      - npm test 

    sudo: required
    dist: trusty
    -language: python
    virtualenv:
      system_site_packages: true
    python: 
      - "3.5"
      - "3.5-dev"
      - "pypy3.5"
    cache: pip
    before_install:
      - sudo apt-get update
      - sudo apt-get -y install python3-pip python-dev
      - sudo pip3 install -U setuptools
      - sudo pip3 install -U virtualenvwrapper
      - python3 -V
      - pip3 -V 
      - cd ./backend/
    install: 
      - sudo pip3 install -r requirements.txt
      - sudo pip3 install .
    script:
      - sudo python3 manage.py test


notifications:
  email: sally20921@snu.ac.kr


    
   
