language: generic
matrix:
  include:
    -language: python
    virtualenv:
      system_site_packages: true
    python: 3.5.1
    before_install: 
      - cd ./backend/
    install: 
      - pip install -r requirements.txt
    script:
      - python manage.py test

    -language: node_js
    node_js: 6.9.4
    before_install: 
      - cd ./frontend/
    install:
      - npm install 
    script: 
      - npm test 

    -language: python
    virtualenv:
      system_site_packages: true
    python: 3.5.1
    cache: pip
    before_install: 
      - cd ./backend/
    install: 
      - pip install --upgrade pip
      - pip install -r requirements.txt
    script:
      - pytest


notifications:
  email: sally20921@snu.ac.kr


    
   
