matrix:
  include:
    - language: python
    python: 3.5.1
    before_install: 
      - cd ./backend/
    install: 
      - pip3 install -r requirements.txt
    script:
      - python3 manage.py test

    - language: node_js
    node_js: 6.9.4
    before_install: 
      - cd ./frontend/
    install:
      - npm install 
    script: 
      - npm test 

    - language: python
    python: 3.5.1
    before_install: 
      - cd ./backend/
    install: 
      - pip3 install -r requirements.txt
    script:
      - python3 manage.py test

notifications:
  email: sally20921@snu.ac.kr


    
   
